In [5]:
from numpy import array, zeros
from random import sample, randint, seed
from colorama import Fore, Style

In [6]:
# These two printing functions only work with quick find as they use direct acess to the root dictionary to retrieve the root

def pre_percolated_board(size, space, final_mark, root, root_dict, board):
    """Prints the board one stage before percolation. Highlights the percolation position. Open positions are black. Closed positions are red."""
    position = 0
    print('[[', end='')
    for row in board:    
        for number in row:
            if position == 0:
                pass
            else:
                if position % size == 0:
                    print()
                    print(' [', end='')

            mark = str(int(number)) + '.'
            
            if mark == '0.':
                if position == final_mark:
                    print(Style.BRIGHT + Fore.RED + mark, end='')
                else:
                    print(Fore.RED + mark, end='')
                print(Style.RESET_ALL, end='')
            else:
                print(mark, end='')
            if (position + 1) % size == 0:
                print(']', end='')
                if position + 1 == space:
                    print(']')
            else:
                print(' ', end='')

            position += 1


def percolated_board(size, space, final_mark, root, root_dict, board):
    """Prints the board at percolation. Highlights the percolation position. Full positions are blue. Open positions are black. Closed positions are red."""
    position = 0
    print('[[', end='')
    for row in board:    
        for number in row:
            if position == 0:
                pass
            else:
                if position % size == 0:
                    print()
                    print(' [', end='')

            mark = str(int(number)) + '.'
            
            if root_dict[position] == root:
                if position == final_mark:
                    print(Style.BRIGHT + Fore.BLUE + mark, end='')
                else:
                    print(Fore.BLUE + mark, end='')
                print(Style.RESET_ALL, end='')
            else:
                if mark == '0.':
                    print(Fore.RED + mark, end='')
                    print(Style.RESET_ALL, end='')
                else:
                    print(mark, end='')
            
            if (position + 1) % size == 0:
                print(']', end='')
                if position + 1 == space:
                    print(']')
            else:
                print(' ', end='')

            position += 1
            
# Alternative Printing by building a list and calling a function- used in final model in the Percolation Module
def p_board(size, space, root, root_dict, board):  
    position = 0
    new_board = ['[[']
    for row in board:    
        for number in row:
            if position == 0:
                pass
            else:
                if position%size == 0:
                    new_board.append('\n [')

            mark = str(int(number)) + '.'
            new_board.append(mark)

            if (position + 1)%size == 0:
                new_board.append(']')

                if position+1 == space:
                    new_board.append(']')
            else:
                new_board.append(' ')

            position += 1
    
    return ''.join(new_board)
#     position = 0
#     for mark in a:
#         if (mark == '0') or (mark == '1'):
#             if root_dict[position] == root:
#                 print(Style.BRIGHT + Fore.BLUE + mark, end='')
#                 print(Style.RESET_ALL, end='')
#             else:
#                 print(mark, end='')
#             position += 1
#         else:
#             print(mark, end='')

In [7]:
def generate_roots(n):
    """Generate and return dictionary to keep track of roots for matrix with n elements"""
    roots = dict()
    for i in range(n):
        roots[i] = i
    return roots

def quick_find(p, q, roots):
    """Update dictionary of roots using quick find algorithm setting all numbers with root of the first number to the root of the second number"""
    for num, root in roots.items():
        if root == p:
            roots[num] = q   

def quick_union(root_p, root_q, roots):
    """Update dictionary of roots using quick union algorithm setting the root of the first number to the root of the second number"""
    roots[root_p] = root_q

def find_root(n, roots):
    """Returns the root of a number for the quick union algorithm"""
    while roots[n] != n:
        n = roots[n]
    return n
    
def connected(a, b, roots):
    """Call quick find method to update roots if the numbers have different roots"""
    p = roots[a]
    q = roots[b]
    if p != q:
        quick_find(p, q, roots)
        
def connected_qu(a, b, roots):
    """Call quick union method to update roots if the numbers have different roots"""
    p = find_root(a, roots)
    q = find_root(b, roots)
    if p != q:
        quick_union(p, q, roots)

# Tested at size of 120
# Fastest way to check percolation!

def percolated(size, space, roots):
    """Check if the numbers have percolated"""
    top_row = set()
    bottom_row = set()
    
    for i in range(size):
        top_row.add(roots[i])
    for i in range(space-size, space):
        bottom_row.add(roots[i])
    
    common_roots = top_row.intersection(bottom_row)
    
    if len(common_roots) != 0:
            return True, list(common_roots)[0]
    
    return False, 0

# the best percolation algorithm using find_root function 
def percolated_qu(size, space, roots):
    """Check if the numbers have percolated"""
    top_row = set()
    bottom_row = set()
    
    for i in range(size):
        top_row.add(find_root(i, roots))
    for i in range(space-size, space):
        bottom_row.add(find_root(i, roots))
    
    common_roots = top_row.intersection(bottom_row)
    
    if len(common_roots) != 0:
            return True, list(common_roots)[0]
    
    return False, 0
   
# Second fastest -> performance times close to the set way- about one or two seconds slower 
def percolated_2(size, space, roots):   
    top_row = []
    bottom_row = []
    for i in range(size):
        top_row.append(roots[i])
    for i in range(space - size, space):
        bottom_row.append(roots[i])
    for root in top_row:
        if root in bottom_row:
            return True, root
    return False, 0

# Second slowest -> about one or two seconds longer than second fastest
def percolated_3(size, space, roots):
    top_row = []
    bottom_row = []
    for i in range(size):
        top_row.append(roots[i])
    for i in range(space - size, space):
        bottom_row.append(roots[i])
    for top_root in top_row:
        for bottom_root in bottom_row:
            if top_root == bottom_root:
                return True, top_root
    return False, 0

# Slowest -> almost twice as slow as using sets
def percolated_4(size, space, roots):
    for top_number in range(size):
        top_root = roots[top_number]
        for bottom_number in range(space - size, space):
            if top_root == roots[bottom_number]:
                return True, top_root
            
    return False, 0

In [8]:
import time

def game(size, show_board, connected, percolated):
    board = zeros((size, size))

    space = size ** 2
    top_edge = 0
    bottom_edge = size - 1 

    root_dict = generate_roots(space)
    seed(5)
    marks = sample(range(0,  space), space)

    count = 1
    start = time.time()
    for mark in marks:
        row = (mark) // size
        column = (mark) % size
        position = (row, column)
        previous_board = board.copy()
        board[row, column] = 1


        # Positions on board relative to new mark
        above = row - 1
        below = row + 1
        left = column - 1
        right = column + 1

        # Check the position above for connection
        if above >= top_edge:
            if board[above, column] == 1:
                connected(mark, mark - size, root_dict)

        # Check the position below for connection
        if below <= bottom_edge:
            if board[below, column] == 1:
                connected(mark, mark + size, root_dict)

        # Check the position to the left for connection
        if left >= top_edge:
            if board[row, left] == 1:
                connected(mark, mark - 1, root_dict)

        # Check the position to the right for connection
        if right <= bottom_edge:
            if board[row, right] == 1:
                connected(mark, mark + 1, root_dict)

        # Check for percolation
        done, root = percolated(size, space, root_dict)
        if done is True:
            percolation = count/space
            end = time.time()
            print(f"Elapsed time: {end - start}\n")
            if (size < 50) and (show_board == True):
                
                # Show the board one step before percolation, highlighting the percolation breaking point
                pre_percolated_board(size, space, mark, root, root_dict, previous_board)
                print("\nDone! The percolation threshold is:", str(round(percolation*100, 2))+"%\n")
                
                # Show the percolated board, highlighting the percolation breaking point
                percolated_board(size, space, mark, root, root_dict, board)

            return percolation
 
        else:
            count += 1

There are four algorithms for checking for percolation. 

Below is a test to see which one is the best performing algorithm.

In [33]:
p1 = game(120, True, connected, percolated)
p2 = game(120, True, connected, percolated_2)
p3 = game(120, True, connected, percolated_3)
p4 = game(120, True, connected, percolated_4)
# Check that the percolation threshold is the same, i.e. the seed worked and all were tested on the same sequence of random numbers
print(p1 == p2 == p3 == p4)
# Show the percolation threshold
print("Threshold", p1)

Elapsed time: 8.34130311012268
Elapsed time: 11.853486061096191
Elapsed time: 14.226254940032959
Elapsed time: 16.75813603401184
True
Threshold 0.5970833333333333


Adapted the best performing percolated function and the connected function for quick union.

Compare the times to quick find.

In [41]:
for size in [51, 100, 175]:
    print(f"Quick Find: size={size}")
    game(size, True, connected, percolated)
    print(f"Quick Union: size={size}")
    game(size, True, connected_qu, percolated_qu)
    print()

Quick Find: size=51
Elapsed time: 0.3008589744567871
Quick Union: size=51
Elapsed time: 0.07298421859741211

Quick Find: size=100
Elapsed time: 3.7826340198516846
Quick Union: size=100
Elapsed time: 0.6655983924865723

Quick Find: size=175
Elapsed time: 37.981724977493286
Quick Union: size=175
Elapsed time: 3.0255520343780518



In [48]:
game(6, True, connected, percolated)

Elapsed time: 0.0005230903625488281

[[1. 1. 0. 1. 0. 1.]
 [0. 1. 0. 0. 0. 1.]
 [1. 0. 0. 1. 1. 1.]
 [1. 0. 1. 0. 1. 0.]
 [1. 1. 0. 0. 0. 1.]
 [0. 1. 1. 1. 1. 0.]]

Done! The percolation threshold is: 58.33%

[[1. 1. 0. 1. 0. 1.]
 [1. 1. 0. 0. 0. 1.]
 [1. 0. 0. 1. 1. 1.]
 [1. 0. 1. 0. 1. 0.]
 [1. 1. 0. 0. 0. 1.]
 [0. 1. 1. 1. 1. 0.]]


0.5833333333333334

In [50]:
# Note the visualizer does not work on the percolated board because of the how quick union keeps track of roots
game(6, True, connected_qu, percolated_qu)

Elapsed time: 0.0009348392486572266

[[1. 1. 0. 1. 0. 1.]
 [0. 1. 0. 0. 0. 1.]
 [1. 0. 0. 1. 1. 1.]
 [1. 0. 1. 0. 1. 0.]
 [1. 1. 0. 0. 0. 1.]
 [0. 1. 1. 1. 1. 0.]]

Done! The percolation threshold is: 58.33%

[[1. 1. 0. 1. 0. 1.]
 [1. 1. 0. 0. 0. 1.]
 [1. 0. 0. 1. 1. 1.]
 [1. 0. 1. 0. 1. 0.]
 [1. 1. 0. 0. 0. 1.]
 [0. 1. 1. 1. 1. 0.]]


0.5833333333333334